# Generated by Django 3.2.12 on 2022-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_raroc_py', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculararoc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fluxo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
