name: GitHub Actions Demo
on:
  release:
    types: [published]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Debug version
        id: Debug
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: executing remote ssh commands using ssh key
        uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.GCP_IP  }}
            USER_NAME : ubuntu
            
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            pwd
            ls
            '
